import { api } from '@/lib/api/client';
import { GeneratedShape } from '@/modules/ai/types/chat.type';

export interface Asset {
    id: string;
    name: string;
    type: string;
    url: string;
    job_id: string;
    session_id: string;
    created_at: string;
}

export interface AssetMeta {
    id: string;
    asset_id: string;
    part_name?: string;
    component_of?: string;
    position_json?: Record<string, any>;
    material_json?: Record<string, any>;
    image_paths_json?: any[];
    is_composite_of_json?: any[];
    used_for_json?: any[];
    metadata?: Record<string, any>; // For extra/legacy fields
}

class AssetService {
    //  Fetch assets generated by a specific job
    async fetchAssets(jobId?: string): Promise<Asset[]> {
        try {
            const params: any = {};
            if (jobId) params.job_id = jobId;

            const response = await api.get<Asset[]>('/assets', { params });
            return response.data;
        } catch (error) {
            console.error('Failed to fetch assets:', error);
            return [];
        }
    }

    // Client-side search for related assets
    async searchAssets(query: string): Promise<Asset[]> {
        if (!query || query.length < 2) return [];

        try {
            // Fetch all assets (no job_id)
            const allAssets = await this.fetchAssets();
            const lowerQuery = query.toLowerCase();

            return allAssets.filter(asset => {
                // Filter by name, uri (filename), or type
                const matchesName = asset.name?.toLowerCase().includes(lowerQuery);
                const matchesUri = asset.url?.toLowerCase().includes(lowerQuery); // asset.url usually contains the filename/uri

                // Optional: Check metadata if available (not in base Asset interface but might be useful if extended)
                return matchesName || matchesUri;
            });
        } catch (error) {
            console.error('Failed to search assets:', error);
            return [];
        }
    }

    //  Fetch metadata for a specific asset
    async fetchAssetMeta(assetId: string): Promise<AssetMeta[]> {
        try {
            const response = await api.get<AssetMeta[]>('/asset-meta', {
                params: { asset_id: assetId }
            });
            return response.data;
        } catch (error) {
            console.error('Failed to fetch asset metadata:', error);
            return [];
        }
    }

    // Register a new asset (e.g. for manual imports)
    async createAsset(payload: {
        job_id: string;
        asset_type: string;
        uri: string;
        storage_provider: string;
        metadata_json?: any;
    }): Promise<Asset> {
        const response = await api.post<Asset>('/assets', payload);
        return response.data;
    }

    // Register metadata for an asset
    async createAssetMeta(payload: {
        asset_id: string;
        part_name?: string;
        component_of?: string;
        position_json?: Record<string, any>;
        material_json?: Record<string, any>;
        metadata?: Record<string, any>;
    }): Promise<AssetMeta> {
        const response = await api.post<AssetMeta>('/asset-meta', payload);
        return response.data;
    }

    // Map backend assets and metadata to frontend GeneratedShape format
    async mapToGeneratedShape(jobId: string, assets: Asset[]): Promise<GeneratedShape | null> {
        console.log('[AssetService] mapToGeneratedShape called for job:', jobId, 'with', assets.length, 'assets');

        try {
            // Find the primary model asset (SDF or GLB)
            const modelAsset = assets.find(a => a.url?.toLowerCase().endsWith('.sdf') || a.url?.toLowerCase().endsWith('.glb'));
            if (!modelAsset) {
                console.warn('[AssetService] No model asset found in:', assets.map(a => a.url));
                return null;
            }

            console.log('[AssetService] Found model asset:', modelAsset.url);

            // Fetch metadata for parts
            const metadata = await this.fetchAssetMeta(jobId);
            console.log('[AssetService] Fetched metadata:', metadata.length, 'entries');

            const parts = metadata.map(m => ({
                id: m.id,
                name: m.part_name || 'Unnamed Part',
                category: m.component_of ? 'Component' : 'Main Structure',
                role: 'structural' as const,
                placement: m.position_json ? {
                    x: m.position_json.x || 0,
                    y: m.position_json.y || 0,
                    z: m.position_json.z || 0
                } : undefined,
                mesh_file: m.asset_id // Reference to the asset
            }));

            const scadCode = await this.fetchScadContent(assets);
            console.log('[AssetService] SCAD code fetched:', scadCode ? `${scadCode.length} chars` : 'none');

            const shape = {
                id: modelAsset.id,
                type: 'generic' as const,
                name: modelAsset.name,
                description: 'Generated Model',
                hasSimulation: true,
                geometry: {
                    parts: parts,
                    joints: [], // Can be expanded if backend supports joints table
                    physics: {}
                },
                createdAt: new Date(modelAsset.created_at),
                assetId: modelAsset.id,
                sdfUrl: modelAsset.url,
                scadCode: scadCode,
                specification: {
                    model_name: modelAsset.name,
                    parts: parts
                }
            };

            console.log('[AssetService] Mapped shape:', shape.name, 'ID:', shape.id);
            return shape;
        } catch (err) {
            console.error('[AssetService] Error mapping assets to shape:', err);
            return null;
        }
    }

    // Helper to find and fetch SCAD code from assets
    private async fetchScadContent(assets: Asset[]): Promise<string | undefined> {
        const scadAsset = assets.find(a => a.url?.toLowerCase().endsWith('.scad'));
        if (!scadAsset) return undefined;

        try {
            const response = await fetch(scadAsset.url);
            if (response.ok) {
                return await response.text();
            }
        } catch (e) {
            console.warn('Failed to fetch SCAD content:', e);
        }
        return undefined;
    }
}

export const assetService = new AssetService();
